# Generated by Django 5.2.17 on 2026-09-11 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utileria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnicaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificaciones', models.TextField()),
                ('dimensiones', models.CharField(max_length=100)),
                ('peso_gramos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('es_toxico', models.BooleanField(default=False)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='utileria.producto')),
            ],
        ),
    ]
