# Generated by Django 5.2.17 on 2026-09-18 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utileria', '0004_remove_pedido_cantidad_remove_pedido_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='utileria.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='utileria.proveedor'),
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(default='Boleta', max_length=50)),
                ('serie_numero', models.CharField(max_length=50)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='utileria.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='utileria.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasillo', models.CharField(max_length=50)),
                ('estante', models.CharField(max_length=50)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='utileria.producto')),
            ],
        ),
    ]
