# Generated by Django 5.2.17 on 2026-09-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='deporte',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='ACTIVA', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.CharField(max_length=5),
        ),
    ]
